In [1]:
import numpy as np

In [2]:
def svd_from_scratch(X):
    """
    Computes the Singular Value Decomposition (SVD) of a matrix X **from scratch** 
    (without using prebuilt SVD functions).

    The decomposition follows:
        X = UΣVᴴ

    where:
    - `U` (Left singular vectors): Orthonormal matrix of shape (n, n).
    - `Σ` (Sigma): Diagonal matrix containing singular values of shape (n, m).
    - `Vᴴ` (Right singular vectors, transposed): Orthonormal matrix of shape (m, m).

    **Steps:**
    1. Compute `XXᴴ` and `XᴴX` (to find left and right singular vectors).
    2. Compute eigenvalues and eigenvectors of these matrices.
    3. Sort eigenvalues in descending order and rearrange eigenvectors accordingly.
    4. Compute singular values as the square root of sorted eigenvalues.
    5. Construct Σ (Sigma) matrix with singular values along the diagonal.

    Parameters:
    -----------
    X : ndarray
        The input matrix of shape (n, m).

    Returns:
    --------
    U : ndarray
        Matrix containing left singular vectors (shape: (n, n)).
    Σ : ndarray
        Diagonal matrix with singular values (shape: (n, m)).
    Vᴴ : ndarray
        Transposed right singular vectors (shape: (m, m)).

    Example usage:
    --------------
    >>> X = np.array([[4, 0, 2], [3, -5, 1], [2, 3, 0]], dtype=float)
    >>> U, Sigma, VT = svd_from_scratch(X)
    >>> print(U)
    >>> print(Sigma)
    >>> print(VT)
    """


    # Step 1: Compute XXᴴ and XᴴX
    XXT = X @ X.T  # Left singular vectors
    XTX = X.T @ X  # Right singular vectors
    
    # Step 2: Compute eigenvalues and eigenvectors
    eigvals_U, U = np.linalg.eigh(XXT)
    eigvals_V, V = np.linalg.eigh(XTX)

    # Step 3: Sort eigenvalues and corresponding eigenvectors in descending order
    sorted_indices_U = np.argsort(eigvals_U)[::-1]
    sorted_indices_V = np.argsort(eigvals_V)[::-1]

    U = U[:, sorted_indices_U]
    V = V[:, sorted_indices_V]
    
    # Step 4: Compute singular values as square roots of sorted eigenvalues
    singular_values = np.sqrt(np.maximum(eigvals_U[sorted_indices_U], 0))

    # Step 5: Construct Σ (Sigma) matrix
    Sigma = np.zeros_like(X, dtype=float)
    np.fill_diagonal(Sigma, singular_values)

    return U, Sigma, V.T  # V needs to be transposed for final decomposition

In [3]:
# Example: Apply to a 3×3 matrix
X = np.array([[4, 0, 2], 
              [3, -5, 1], 
              [2, 3, 0]], dtype=float)

U, Sigma, VT = svd_from_scratch(X)

print("U matrix:\n", U)
print("Sigma matrix:\n", Sigma)
print("V^T matrix:\n", VT)

# Verify the decomposition
reconstructed_X = U @ Sigma @ VT
print("\nReconstructed X:\n", reconstructed_X)

U matrix:
 [[-0.46771169  0.65837746  0.58973291]
 [-0.87373693 -0.24359178 -0.42100693]
 [ 0.13352738  0.71218128 -0.68917942]]
Sigma matrix:
 [[6.62341414 0.         0.        ]
 [0.         4.84499147 0.        ]
 [0.         0.         0.81021153]]
V^T matrix:
 [[-0.63788896  0.72006169 -0.27314618]
 [ 0.68670854  0.69236504  0.22149949]
 [-0.34861017  0.04627974  0.93612453]]

Reconstructed X:
 [[ 4.00000000e+00  2.43353243e-15  2.00000000e+00]
 [ 3.00000000e+00 -5.00000000e+00  1.00000000e+00]
 [ 2.00000000e+00  3.00000000e+00  7.32911987e-16]]
